alchemy_admin:
    service:
        title: hello
        name: hello

easy_admin:
    entities:
        Bar:
            class: App\Entity\Bar
            list:
                fields:
                    - id
                    - baz
            form:
                fields:
                    - { property: 'baz', type: text }
